FileSharingApplication/Areas/Share/Models/FileShare.cs
using System;
using System.IO;
using FileSharingApplication.Account.Models;
using FileSharingApplication.Models;

namespace FileSharingApplication.Areas.Share.Models
{
    public class FileShare : Entity
    {

        public static FileShare CreateNew(string bucketName, User owner, string fileName)
        {
            var fileShare = new FileShare()
            {
                Bucket = bucketName,
                CreationDate = DateTime.Now,
                Owner = owner,
                Id = Guid.NewGuid(),
                Title = fileName
            };
            fileShare.GenerateKey(fileName);

            return fileShare;
        }

        public DateTime CreationDate { get; set; }

        public DateTime? LastDownloadDate { get; set; }

        private string GetUrl(bool ssl)
        {
            return string.Format("http{0}://{1}.s3.amazonaws.com/{2}",
                ssl ? "s" : string.Empty,
                this.Bucket,
                this.Key);
        }

        public string Title { get; set; }

        /// <summary>
        /// Full url at Amazon S3
        /// </summary>
        public virtual string Url
        {
            get { return GetUrl(false); }
        }

        /// <summary>
        /// Full ssl url at Amazon S3
        /// </summary>
        public virtual string SslUrl
        {
            get { return GetUrl(true); }
        }

        /// <summary>
        /// AWS Bucket Name S3
        /// </summary>
        public string Bucket { get; set; }

        /// <summary>
        /// Key/filename from object Request from AWS S3
        /// </summary>
        public string Key { get; set; }

        public virtual User Owner { get; set; }

        public virtual void GenerateKey(string fileName)
        {
            var extension = Path.GetExtension(fileName);
            var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(fileName);
            var uniqueChars = Guid.NewGuid().ToString().Replace("-", string.Empty);

            Key = string.Concat(fileNameWithoutExtension, uniqueChars, extension);
        }
    }
}

FileSharingApplication/Areas/Share/Controllers/FileSharesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FileSharingApplication.Areas.Share.Models;
using FileSharingApplication.Areas.Share.Services;
using FileSharingApplication.Models.UnitOfWork;


namespace FileSharingApplication.Areas.Share.Controllers
{
    [Authorize]
    public class FileSharesController : Controller
    {
        // GET: Share/FileShares

        public ActionResult Index()
        {
            var context = DataContext.JoinOrCreate();

            var files = context.FileShares
                .Where(x => x.Owner.Id == FileSharingApplication.Account.Models.User.Current.Id);

            return View(files);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(HttpPostedFileBase file)
        {
            var service = AmazonS3Service.CreateNew();

            var share = FileShare.CreateNew("artur2", null, file.FileName);

            return await service.UploadFileAsync(file.InputStream, "artur2", share.Key)
                  .ContinueWith<ActionResult>(x =>
              {
                  if (x.IsCompleted && !x.IsFaulted)
                  {
                      var context = DataContext.CreateContextless();
                      share.Owner = FileSharingApplication.Account.Models.User.Current;
                      context.FileShares.Add(share); // i was right about IEntityChangeTracker 
                      context.SaveChanges();

                      return RedirectToAction("Index");
                  }

                  return RedirectToRoute("Error", new { action = "ServerError" });
              });
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var share = context.FileShares.Find(id);
            if (share == null)
                return RedirectToRoute("Error", new { action = "NotFound" });

            var service = AmazonS3Service.CreateNew();

            return await service.DeleteFileAsync(share.Bucket, share.Key).ContinueWith(x =>
             {
                 if (x.IsCompleted && !x.IsFaulted)
                 {
                     var dbContext = DataContext.CreateContextless();
                     var sharing = dbContext.FileShares.Find(id);
                     dbContext.FileShares.Remove(sharing);
                     dbContext.SaveChanges();

                     return RedirectToAction("Index");
                 }

                 return RedirectToRoute("Error", new { action = "ServerError" });
             });
        }
    }
}

FileSharingApplication/Areas/Share/Views/FileShares/Add.cshtml
@section HeadTitle
{
    <h1>File Upload</h1>
}

@using (Html.BeginForm("Add", "FileShares", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
{
    <div class="form-group">
        <label for="file">File</label>
        <input type="file" name="file" id="file"/>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
}

FileSharingApplication/Areas/Share/Views/FileShares/Index.cshtml
@model IQueryable<FileSharingApplication.Areas.Share.Models.FileShare>
@section HeadTitle
{
    <h1>Files</h1>
}
@*TODO: Add Grid*@
<div class="row">
    <div class="col-xs-6 col-md-4">
        Title
    </div>
    <div class="col-xs-6 col-md-4">
        Upload date
    </div>
    <div class="col-xs-6 col-md-4">
        Actions
    </div>
</div>
@foreach (var share in Model)
{
    <br/>
    <div class="row">
        <div class="col-xs-6 col-md-4">
            <a href="@share.Url">@share.Title</a>
        </div>
        <div class="col-xs-6 col-md-4">
            @share.CreationDate
        </div>
        <div class="col-xs-6 col-md-4">
            <a href="@Url.Action("Delete", "FileShares", new { area = "Share", id = share.Id })" class="btn btn-default">Delete</a>
        </div>
    </div>
}

<a href="@Url.Action("Add", "FileShares", new { area = "Share" })" class="btn btn-default">Upload</a>