FileSharingApplication/Areas/Account/Controllers/UsersController.cs
using System;
using System.Web;
using System.Web.Mvc;
using FileSharingApplication.Account.Models;
using FileSharingApplication.Account.Stores;
using FileSharingApplication.Models.UnitOfWork;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace FileSharingApplication.Areas.Account.Controllers
{
    public class UsersController : Controller
    {

        private UserManager<User, Guid> _userManager;

        public UserManager<User, Guid> UserManager
        {
            get
            {
                if (_userManager == null)
                    _userManager = new UserManager<User, Guid>(new UserStore());

                return _userManager;
            }
        }

        public IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        // GET: Account/Users
        public ActionResult Index()
        {
            return View();
        }

        //---------------- TODO --------------- 
        // Add Views

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(string login, string password)
        {
            var user = UserManager.FindByName(login);

            if (user != null &&
                UserManager.HasPassword(user.Id) &&
                UserManager.CheckPassword(user, password))
            {
                var identity = UserManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);

                AuthenticationManager.SignIn(new AuthenticationProperties()
                {
                    IsPersistent = true
                }, identity);

                return RedirectToAction("Index", "FileShares", new { area = "Share" });
            }

            ModelState.AddModelError("_FORM", "Check your login or password");

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Logoff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return Redirect("/");
        }

        [HttpGet]
        public ActionResult Register()
        {
            var model = new RegisterModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var context = DataContext.JoinOrCreate();

            var user = new User()
            {
                Id = Guid.NewGuid(),
                UserName = model.Login
            };
            UserManager.Create(user, model.Password);

            var identity = UserManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignIn(new AuthenticationProperties()
            {
                IsPersistent = true
            }, identity);

            context.SaveChanges();

            return Redirect("/");
        }

        [Authorize]
        public ActionResult Cabinet()
        {
            var user = FileSharingApplication.Account.Models.User.Current;

            return View(user);
        }
    }
}

FileSharingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.RouteUrl("Index")"><span class="glyphicon glyphicon-home"></span></a>
                    </li>
                    <li>
                        <a href="@Url.RouteUrl("Default", new { action = "About", controller = "Home" })"><span class="glyphicon glyphicon-question-sign"></span></a>
                    </li>
                    @*<li>
                            <a href="@Url.RouteUrl("Default", new { action = "Contact", controller = "Home" })">Contacts</a>
                        </li>*@

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Logoff", "Users", new { area = "Account" })"><span class="glyphicon glyphicon-log-out"></span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "FileShares", new { area = "Share" })">
                                <span class="glyphicon glyphicon-th-list">
                                </span> Files
                            </a>
                        </li>
                        <li>
                            <p class="navbar-text">Signed in as <a href="@Url.Action("Cabinet", "Users", new { area = "Account" })">@User.Identity.Name</a></p>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Login", "Users", new { area = "Account" })">
                                <span class="glyphicon glyphicon-log-in">
                                </span>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderSection("HeadTitle", false)
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>